SEED_UNIVERSITIES = [
    {
        "id": 1,
        "name": "Massachusetts Institute of Technology (MIT)",
        "base_url": "https://www.mit.edu",
        "domain": "mit.edu",
    },
    {
        "id": 2,
        "name": "University of Cambridge",
        "base_url": "https://www.cam.ac.uk",
        "domain": "cam.ac.uk",
    },
    {
        "id": 3,
        "name": "University of Oxford",
        "base_url": "https://www.ox.ac.uk",
        "domain": "ox.ac.uk",
    },
    {
        "id": 4,
        "name": "Harvard University",
        "base_url": "https://www.harvard.edu",
        "domain": "harvard.edu",
    },
    {
        "id": 5,
        "name": "Stanford University",
        "base_url": "https://www.stanford.edu",
        "domain": "stanford.edu",
    },
    {
        "id": 6,
        "name": "Imperial College London",
        "base_url": "https://www.imperial.ac.uk",
        "domain": "imperial.ac.uk",
    },
    {
        "id": 7,
        "name": "ETH Zurich",
        "base_url": "https://www.ethz.ch",
        "domain": "ethz.ch",
    },
    {
        "id": 8,
        "name": "National University of Singapore (NUS)",
        "base_url": "https://www.nus.edu.sg",
        "domain": "nus.edu.sg",
    },
    {
        "id": 9,
        "name": "UCL",
        "base_url": "https://www.ucl.ac.uk",
        "domain": "ucl.ac.uk",
    },
    {
        "id": 10,
        "name": "University of California, Berkeley (UCB)",
        "base_url": "https://www.berkeley.edu",
        "domain": "berkeley.edu",
    },
    {
        "id": 11,
        "name": "University of Chicago",
        "base_url": "https://www.uchicago.edu",
        "domain": "uchicago.edu",
    },
    {
        "id": 12,
        "name": "University of Pennsylvania",
        "base_url": "https://www.upenn.edu",
        "domain": "upenn.edu",
    },
    {
        "id": 13,
        "name": "Cornell University",
        "base_url": "https://www.cornell.edu",
        "domain": "cornell.edu",
    },
    {
        "id": 14,
        "name": "The University of Melbourne",
        "base_url": "https://www.unimelb.edu.au",
        "domain": "unimelb.edu.au",
    },
    {
        "id": 15,
        "name": "California Institute of Technology (Caltech)",
        "base_url": "https://www.caltech.edu",
        "domain": "caltech.edu",
    },
    {
        "id": 16,
        "name": "Yale University",
        "base_url": "https://www.yale.edu",
        "domain": "yale.edu",
    },
    {
        "id": 17,
        "name": "Peking University",
        "base_url": "https://www.pku.edu.cn",
        "domain": "pku.edu.cn",
    },
    {
        "id": 18,
        "name": "Princeton University",
        "base_url": "https://www.princeton.edu",
        "domain": "princeton.edu",
    },
    {
        "id": 19,
        "name": "The University of New South Wales (UNSW Sydney)",
        "base_url": "https://www.unsw.edu.au",
        "domain": "unsw.edu.au",
    },
    {
        "id": 20,
        "name": "The University of Sydney",
        "base_url": "https://www.sydney.edu.au",
        "domain": "sydney.edu.au",
    },
    {
        "id": 21,
        "name": "University of Toronto",
        "base_url": "https://www.utoronto.ca",
        "domain": "utoronto.ca",
    },
    {
        "id": 22,
        "name": "The University of Edinburgh",
        "base_url": "https://www.ed.ac.uk",
        "domain": "ed.ac.uk",
    },
    {
        "id": 23,
        "name": "Columbia University",
        "base_url": "https://www.columbia.edu",
        "domain": "columbia.edu",
    },
    {
        "id": 24,
        "name": "Université PSL",
        "base_url": "https://www.univ-psl.fr",
        "domain": "univ-psl.fr",
    },
    {
        "id": 25,
        "name": "Tsinghua University",
        "base_url": "https://www.tsinghua.edu.cn",
        "domain": "tsinghua.edu.cn",
    },
    {
        "id": 26,
        "name": "Nanyang Technological University, Singapore (NTU Singapore)",
        "base_url": "https://www.ntu.edu.sg",
        "domain": "ntu.edu.sg",
    },
    {
        "id": 27,
        "name": "The University of Hong Kong",
        "base_url": "https://www.hku.hk",
        "domain": "hku.hk",
    },
    {
        "id": 28,
        "name": "Johns Hopkins University",
        "base_url": "https://www.jhu.edu",
        "domain": "jhu.edu",
    },
    {
        "id": 29,
        "name": "The University of Tokyo",
        "base_url": "https://www.u-tokyo.ac.jp",
        "domain": "u-tokyo.ac.jp",
    },
    {
        "id": 30,
        "name": "University of California, Los Angeles (UCLA)",
        "base_url": "https://www.ucla.edu",
        "domain": "ucla.edu",
    },
    {
        "id": 31,
        "name": "McGill University",
        "base_url": "https://www.mcgill.ca",
        "domain": "mcgill.ca",
    },
    {
        "id": 32,
        "name": "The University of Manchester",
        "base_url": "https://www.manchester.ac.uk",
        "domain": "manchester.ac.uk",
    },
    {
        "id": 33,
        "name": "University of Michigan-Ann Arbor",
        "base_url": "https://www.umich.edu",
        "domain": "umich.edu",
    },
    {
        "id": 34,
        "name": "Australian National University (ANU)",
        "base_url": "https://www.anu.edu.au",
        "domain": "anu.edu.au",
    },
    {
        "id": 35,
        "name": "University of British Columbia",
        "base_url": "https://www.ubc.ca",
        "domain": "ubc.ca",
    },
    {"id": 36, "name": "EPFL", "base_url": "https://www.epfl.ch", "domain": "epfl.ch"},
    {
        "id": 37,
        "name": "Technical University of Munich",
        "base_url": "https://www.tum.de",
        "domain": "tum.de",
    },
    {
        "id": 38,
        "name": "Institut Polytechnique de Paris",
        "base_url": "https://www.polytechnique.edu",
        "domain": "polytechnique.edu",
    },
    {
        "id": 39,
        "name": "New York University (NYU)",
        "base_url": "https://www.nyu.edu",
        "domain": "nyu.edu",
    },
    {
        "id": 40,
        "name": "King's College London",
        "base_url": "https://www.kcl.ac.uk",
        "domain": "kcl.ac.uk",
    },
    {
        "id": 41,
        "name": "Seoul National University",
        "base_url": "https://www.snu.ac.kr",
        "domain": "snu.ac.kr",
    },
    {
        "id": 42,
        "name": "Monash University",
        "base_url": "https://www.monash.edu",
        "domain": "monash.edu",
    },
    {
        "id": 43,
        "name": "The University of Queensland",
        "base_url": "https://www.uq.edu.au",
        "domain": "uq.edu.au",
    },
    {
        "id": 44,
        "name": "Zhejiang University",
        "base_url": "https://www.zju.edu.cn",
        "domain": "zju.edu.cn",
    },
    {
        "id": 45,
        "name": "The London School of Economics and Political Science (LSE)",
        "base_url": "https://www.lse.ac.uk",
        "domain": "lse.ac.uk",
    },
    {
        "id": 46,
        "name": "Kyoto University",
        "base_url": "https://www.kyoto-u.ac.jp",
        "domain": "kyoto-u.ac.jp",
    },
    {
        "id": 47,
        "name": "Delft University of Technology",
        "base_url": "https://www.tudelft.nl",
        "domain": "tudelft.nl",
    },
    {
        "id": 48,
        "name": "Northwestern University",
        "base_url": "https://www.northwestern.edu",
        "domain": "northwestern.edu",
    },
    {
        "id": 49,
        "name": "The Chinese University of Hong Kong (CUHK)",
        "base_url": "https://www.cuhk.edu.hk",
        "domain": "cuhk.edu.hk",
    },
    {
        "id": 50,
        "name": "Fudan University",
        "base_url": "https://www.fudan.edu.cn",
        "domain": "fudan.edu.cn",
    },
    # {
    #     "id": 51,
    #     "name": "Shanghai Jiao Tong University",
    #     "base_url": "https://www.sjtu.edu.cn",
    #     "domain": "sjtu.edu.cn",
    # },
    # {
    #     "id": 52,
    #     "name": "Carnegie Mellon University",
    #     "base_url": "https://www.cmu.edu",
    #     "domain": "cmu.edu",
    # },
    # {
    #     "id": 53,
    #     "name": "University of Amsterdam",
    #     "base_url": "https://www.uva.nl",
    #     "domain": "uva.nl",
    # },
    # {
    #     "id": 54,
    #     "name": "Ludwig-Maximilians-Universität München",
    #     "base_url": "https://www.uni-muenchen.de",
    #     "domain": "uni-muenchen.de",
    # },
    # {
    #     "id": 55,
    #     "name": "University of Bristol",
    #     "base_url": "https://www.bristol.ac.uk",
    #     "domain": "bristol.ac.uk",
    # },
    # {
    #     "id": 56,
    #     "name": "KAIST - Korea Advanced Institute of Science & Technology",
    #     "base_url": "https://www.kaist.ac.kr",
    #     "domain": "kaist.ac.kr",
    # },
    # {
    #     "id": 57,
    #     "name": "Duke University",
    #     "base_url": "https://www.duke.edu",
    #     "domain": "duke.edu",
    # },
    # {
    #     "id": 58,
    #     "name": "University of Texas at Austin",
    #     "base_url": "https://www.utexas.edu",
    #     "domain": "utexas.edu",
    # },
    # {
    #     "id": 59,
    #     "name": "Sorbonne University",
    #     "base_url": "https://www.sorbonne-universite.fr",
    #     "domain": "sorbonne-universite.fr",
    # },
    # {
    #     "id": 60,
    #     "name": "The Hong Kong University of Science and Technology",
    #     "base_url": "https://www.ust.hk",
    #     "domain": "ust.hk",
    # },
    # {
    #     "id": 61,
    #     "name": "KU Leuven",
    #     "base_url": "https://www.kuleuven.be",
    #     "domain": "kuleuven.be",
    # },
    # {
    #     "id": 62,
    #     "name": "University of California, San Diego (UCSD)",
    #     "base_url": "https://www.ucsd.edu",
    #     "domain": "ucsd.edu",
    # },
    # {
    #     "id": 63,
    #     "name": "University of Washington",
    #     "base_url": "https://www.washington.edu",
    #     "domain": "washington.edu",
    # },
    # {
    #     "id": 64,
    #     "name": "University of Illinois at Urbana-Champaign",
    #     "base_url": "https://illinois.edu",
    #     "domain": "illinois.edu",
    # },
    # {
    #     "id": 65,
    #     "name": "The Hong Kong Polytechnic University",
    #     "base_url": "https://www.polyu.edu.hk",
    #     "domain": "polyu.edu.hk",
    # },
    # {
    #     "id": 66,
    #     "name": "Universiti Malaya (UM)",
    #     "base_url": "https://www.um.edu.my",
    #     "domain": "um.edu.my",
    # },
    # {
    #     "id": 67,
    #     "name": "The University of Warwick",
    #     "base_url": "https://warwick.ac.uk",
    #     "domain": "warwick.ac.uk",
    # },
    # {
    #     "id": 68,
    #     "name": "The University of Auckland",
    #     "base_url": "https://www.auckland.ac.nz",
    #     "domain": "auckland.ac.nz",
    # },
    # {
    #     "id": 69,
    #     "name": "National Taiwan University (NTU)",
    #     "base_url": "https://www.ntu.edu.tw",
    #     "domain": "ntu.edu.tw",
    # },
    # {
    #     "id": 70,
    #     "name": "City University of Hong Kong",
    #     "base_url": "https://www.cityu.edu.hk",
    #     "domain": "cityu.edu.hk",
    # },
    # {
    #     "id": 71,
    #     "name": "Université Paris-Saclay",
    #     "base_url": "https://www.universite-paris-saclay.fr",
    #     "domain": "universite-paris-saclay.fr",
    # },
    # {
    #     "id": 72,
    #     "name": "The University of Western Australia",
    #     "base_url": "https://www.uwa.edu.au",
    #     "domain": "uwa.edu.au",
    # },
    # {
    #     "id": 73,
    #     "name": "Brown University",
    #     "base_url": "https://www.brown.edu",
    #     "domain": "brown.edu",
    # },
    # {
    #     "id": 74,
    #     "name": "KTH Royal Institute of Technology",
    #     "base_url": "https://www.kth.se",
    #     "domain": "kth.se",
    # },
    # {
    #     "id": 75,
    #     "name": "University of Leeds",
    #     "base_url": "https://www.leeds.ac.uk",
    #     "domain": "leeds.ac.uk",
    # },
    # {
    #     "id": 76,
    #     "name": "University of Glasgow",
    #     "base_url": "https://www.gla.ac.uk",
    #     "domain": "gla.ac.uk",
    # },
    # {
    #     "id": 77,
    #     "name": "Yonsei University",
    #     "base_url": "https://www.yonsei.ac.kr",
    #     "domain": "yonsei.ac.kr",
    # },
    # {
    #     "id": 78,
    #     "name": "Durham University",
    #     "base_url": "https://www.dur.ac.uk",
    #     "domain": "dur.ac.uk",
    # },
    # {
    #     "id": 79,
    #     "name": "Korea University",
    #     "base_url": "https://www.korea.ac.kr",
    #     "domain": "korea.ac.kr",
    # },
    # {
    #     "id": 80,
    #     "name": "Osaka University",
    #     "base_url": "https://www.osaka-u.ac.jp",
    #     "domain": "osaka-u.ac.jp",
    # },
    # {
    #     "id": 81,
    #     "name": "Trinity College Dublin, The University of Dublin",
    #     "base_url": "https://www.tcd.ie",
    #     "domain": "tcd.ie",
    # },
    # {
    #     "id": 82,
    #     "name": "University of Southampton",
    #     "base_url": "https://www.southampton.ac.uk",
    #     "domain": "southampton.ac.uk",
    # },
    # {
    #     "id": 83,
    #     "name": "Pennsylvania State University",
    #     "base_url": "https://www.psu.edu",
    #     "domain": "psu.edu",
    # },
    # {
    #     "id": 84,
    #     "name": "University of Birmingham",
    #     "base_url": "https://www.birmingham.ac.uk",
    #     "domain": "birmingham.ac.uk",
    # },
    # {
    #     "id": 85,
    #     "name": "Lund University",
    #     "base_url": "https://www.lunduniversity.lu.se",
    #     "domain": "lu.se",
    # },
    # {
    #     "id": 86,
    #     "name": "Universidade de São Paulo",
    #     "base_url": "https://www.usp.br",
    #     "domain": "usp.br",
    # },
    # {
    #     "id": 87,
    #     "name": "Lomonosov Moscow State University",
    #     "base_url": "https://www.msu.ru",
    #     "domain": "msu.ru",
    # },
    # {
    #     "id": 88,
    #     "name": "Universität Heidelberg",
    #     "base_url": "https://www.uni-heidelberg.de",
    #     "domain": "uni-heidelberg.de",
    # },
    # {
    #     "id": 89,
    #     "name": "The University of Adelaide",
    #     "base_url": "https://www.adelaide.edu.au",
    #     "domain": "adelaide.edu.au",
    # },
    # {
    #     "id": 90,
    #     "name": "University of Technology Sydney",
    #     "base_url": "https://www.uts.edu.au",
    #     "domain": "uts.edu.au",
    # },
    # {
    #     "id": 91,
    #     "name": "Tokyo Institute of Technology (Tokyo Tech)",
    #     "base_url": "https://www.titech.ac.jp",
    #     "domain": "titech.ac.jp",
    # },
    # {
    #     "id": 92,
    #     "name": "University of Zurich",
    #     "base_url": "https://www.uzh.ch",
    #     "domain": "uzh.ch",
    # },
    # {
    #     "id": 93,
    #     "name": "Boston University",
    #     "base_url": "https://www.bu.edu",
    #     "domain": "bu.edu",
    # },
    # {
    #     "id": 94,
    #     "name": "Universidad Nacional Autónoma de México (UNAM)",
    #     "base_url": "https://www.unam.mx",
    #     "domain": "unam.mx",
    # },
    # {
    #     "id": 95,
    #     "name": "Universidad de Buenos Aires (UBA)",
    #     "base_url": "https://www.uba.ar",
    #     "domain": "uba.ar",
    # },
    # {
    #     "id": 96,
    #     "name": "Georgia Institute of Technology",
    #     "base_url": "https://www.gatech.edu",
    #     "domain": "gatech.edu",
    # },
    # {
    #     "id": 97,
    #     "name": "University of St Andrews",
    #     "base_url": "https://www.st-andrews.ac.uk",
    #     "domain": "st-andrews.ac.uk",
    # },
    # {
    #     "id": 98,
    #     "name": "Freie Universitaet Berlin",
    #     "base_url": "https://www.fu-berlin.de",
    #     "domain": "fu-berlin.de",
    # },
    # {
    #     "id": 99,
    #     "name": "Purdue University",
    #     "base_url": "https://www.purdue.edu",
    #     "domain": "purdue.edu",
    # },
    # {
    #     "id": 100,
    #     "name": "Pohang University of Science And Technology (POSTECH)",
    #     "base_url": "https://www.postech.ac.kr",
    #     "domain": "postech.ac.kr",
    # },
    # {
    #     "id": 101,
    #     "name": "University of Nottingham",
    #     "base_url": "https://www.nottingham.ac.uk",
    #     "domain": "nottingham.ac.uk",
    # },
    # {
    #     "id": 102,
    #     "name": "University of Wisconsin-Madison",
    #     "base_url": "https://www.wisc.edu",
    #     "domain": "wisc.edu",
    # },
    # {
    #     "id": 103,
    #     "name": "Pontificia Universidad Católica de Chile (UC)",
    #     "base_url": "https://www.uc.cl",
    #     "domain": "uc.cl",
    # },
    # {
    #     "id": 104,
    #     "name": "The University of Sheffield",
    #     "base_url": "https://www.sheffield.ac.uk",
    #     "domain": "sheffield.ac.uk",
    # },
    # {
    #     "id": 105,
    #     "name": "Uppsala University",
    #     "base_url": "https://www.uu.se",
    #     "domain": "uu.se",
    # },
    # {
    #     "id": 106,
    #     "name": "RWTH Aachen University",
    #     "base_url": "https://www.rwth-aachen.de",
    #     "domain": "rwth-aachen.de",
    # },
    # {
    #     "id": 107,
    #     "name": "University of Copenhagen",
    #     "base_url": "https://www.ku.dk",
    #     "domain": "ku.dk",
    # },
    # {
    #     "id": 108,
    #     "name": "Utrecht University",
    #     "base_url": "https://www.uu.nl",
    #     "domain": "uu.nl",
    # },
    # {
    #     "id": 109,
    #     "name": "Aalto University",
    #     "base_url": "https://www.aalto.fi",
    #     "domain": "aalto.fi",
    # },
    # {
    #     "id": 110,
    #     "name": "Newcastle University",
    #     "base_url": "https://www.ncl.ac.uk",
    #     "domain": "ncl.ac.uk",
    # },
    # {
    #     "id": 111,
    #     "name": "University of Alberta",
    #     "base_url": "https://www.ualberta.ca",
    #     "domain": "ualberta.ca",
    # },
    # {
    #     "id": 112,
    #     "name": "University of Waterloo",
    #     "base_url": "https://uwaterloo.ca",
    #     "domain": "uwaterloo.ca",
    # },
    # {
    #     "id": 113,
    #     "name": "Tohoku University",
    #     "base_url": "https://www.tohoku.ac.jp",
    #     "domain": "tohoku.ac.jp",
    # },
    # {
    #     "id": 114,
    #     "name": "University of Helsinki",
    #     "base_url": "https://www.helsinki.fi",
    #     "domain": "helsinki.fi",
    # },
    # {
    #     "id": 115,
    #     "name": "Western University",
    #     "base_url": "https://www.uwo.ca",
    #     "domain": "uwo.ca",
    # },
    # {
    #     "id": 116,
    #     "name": "University of Southern California",
    #     "base_url": "https://www.usc.edu",
    #     "domain": "usc.edu",
    # },
    # {
    #     "id": 117,
    #     "name": "University of Oslo",
    #     "base_url": "https://www.uio.no",
    #     "domain": "uio.no",
    # },
    # {
    #     "id": 118,
    #     "name": "Stockholm University",
    #     "base_url": "https://www.su.se",
    #     "domain": "su.se",
    # },
    # {
    #     "id": 119,
    #     "name": "University of California, Davis",
    #     "base_url": "https://www.ucdavis.edu",
    #     "domain": "ucdavis.edu",
    # },
    # {
    #     "id": 120,
    #     "name": "KIT, Karlsruhe Institute of Technology",
    #     "base_url": "https://www.kit.edu",
    #     "domain": "kit.edu",
    # },
    # {
    #     "id": 121,
    #     "name": "Technical University of Denmark",
    #     "base_url": "https://www.dtu.dk",
    #     "domain": "dtu.dk",
    # },
    # {
    #     "id": 122,
    #     "name": "Humboldt-Universität zu Berlin",
    #     "base_url": "https://www.hu-berlin.de",
    #     "domain": "hu-berlin.de",
    # },
    # {
    #     "id": 123,
    #     "name": "Politecnico di Milano",
    #     "base_url": "https://www.polimi.it",
    #     "domain": "polimi.it",
    # },
    # {
    #     "id": 124,
    #     "name": "Lancaster University",
    #     "base_url": "https://www.lancaster.ac.uk",
    #     "domain": "lancaster.ac.uk",
    # },
    # {
    #     "id": 125,
    #     "name": "Eindhoven University of Technology",
    #     "base_url": "https://www.tue.nl",
    #     "domain": "tue.nl",
    # },
    # {
    #     "id": 126,
    #     "name": "University of Basel",
    #     "base_url": "https://www.unibas.ch",
    #     "domain": "unibas.ch",
    # },
    # {
    #     "id": 127,
    #     "name": "Leiden University",
    #     "base_url": "https://www.universiteitleiden.nl",
    #     "domain": "universiteitleiden.nl",
    # },
    # {
    #     "id": 128,
    #     "name": "University of Bern",
    #     "base_url": "https://www.unibe.ch",
    #     "domain": "unibe.ch",
    # },
    # {
    #     "id": 129,
    #     "name": "University of Geneva",
    #     "base_url": "https://www.unige.ch",
    #     "domain": "unige.ch",
    # },
    # {
    #     "id": 130,
    #     "name": "Chalmers University of Technology",
    #     "base_url": "https://www.chalmers.se",
    #     "domain": "chalmers.se",
    # },
    # {
    #     "id": 131,
    #     "name": "Macquarie University (Sydney, Australia)",
    #     "base_url": "https://www.mq.edu.au",
    #     "domain": "mq.edu.au",
    # },
    # {
    #     "id": 132,
    #     "name": "University of Vienna",
    #     "base_url": "https://www.univie.ac.at",
    #     "domain": "univie.ac.at",
    # },
    # {
    #     "id": 133,
    #     "name": "Sapienza University of Rome",
    #     "base_url": "https://www.uniroma1.it",
    #     "domain": "uniroma1.it",
    # },
    # {
    #     "id": 134,
    #     "name": "University of North Carolina at Chapel Hill",
    #     "base_url": "https://www.unc.edu",
    #     "domain": "unc.edu",
    # },
    # {
    #     "id": 135,
    #     "name": "Texas A&M University",
    #     "base_url": "https://www.tamu.edu",
    #     "domain": "tamu.edu",
    # },
    # {
    #     "id": 136,
    #     "name": "Michigan State University",
    #     "base_url": "https://msu.edu",
    #     "domain": "msu.edu",
    # },
    # {
    #     "id": 137,
    #     "name": "University of Science and Technology of China",
    #     "base_url": "https://www.ustc.edu.cn",
    #     "domain": "ustc.edu.cn",
    # },
    # {
    #     "id": 138,
    #     "name": "Universiti Sains Malaysia (USM)",
    #     "base_url": "https://www.usm.my",
    #     "domain": "usm.my",
    # },
    # {
    #     "id": 139,
    #     "name": "University of Groningen",
    #     "base_url": "https://www.rug.nl",
    #     "domain": "rug.nl",
    # },
    # {
    #     "id": 140,
    #     "name": "RMIT University",
    #     "base_url": "https://www.rmit.edu.au",
    #     "domain": "rmit.edu.au",
    # },
    # {
    #     "id": 141,
    #     "name": "Nanjing University",
    #     "base_url": "https://www.nju.edu.cn",
    #     "domain": "nju.edu.cn",
    # },
    # {
    #     "id": 142,
    #     "name": "Université de Montréal",
    #     "base_url": "https://www.umontreal.ca",
    #     "domain": "umontreal.ca",
    # },
    # {
    #     "id": 143,
    #     "name": "Aarhus University",
    #     "base_url": "https://international.au.dk",
    #     "domain": "au.dk",
    # },
    # {
    #     "id": 144,
    #     "name": "King Abdulaziz University (KAU)",
    #     "base_url": "https://www.kau.edu.sa",
    #     "domain": "kau.edu.sa",
    # },
    # {
    #     "id": 145,
    #     "name": "Queen Mary University of London",
    #     "base_url": "https://www.qmul.ac.uk",
    #     "domain": "qmul.ac.uk",
    # },
    # {
    #     "id": 146,
    #     "name": "Rice University",
    #     "base_url": "https://www.rice.edu",
    #     "domain": "rice.edu",
    # },
    # {
    #     "id": 147,
    #     "name": "Sungkyunkwan University (SKKU)",
    #     "base_url": "https://www.skku.edu",
    #     "domain": "skku.edu",
    # },
    # {
    #     "id": 148,
    #     "name": "University of Bath",
    #     "base_url": "https://www.bath.ac.uk",
    #     "domain": "bath.ac.uk",
    # },
    # {
    #     "id": 149,
    #     "name": "Indian Institute of Technology Bombay (IITB)",
    #     "base_url": "https://www.iitb.ac.in",
    #     "domain": "iitb.ac.in",
    # },
    # {
    #     "id": 150,
    #     "name": "Universitat Autònoma de Barcelona",
    #     "base_url": "https://www.uab.cat",
    #     "domain": "uab.cat",
    # },
    # {
    #     "id": 151,
    #     "name": "The Ohio State University",
    #     "base_url": "https://www.osu.edu",
    #     "domain": "osu.edu",
    # },
    # {
    #     "id": 152,
    #     "name": "Wageningen University & Research",
    #     "base_url": "https://www.wur.nl",
    #     "domain": "wur.nl",
    # },
    # {
    #     "id": 153,
    #     "name": "University of Exeter",
    #     "base_url": "https://www.exeter.ac.uk",
    #     "domain": "exeter.ac.uk",
    # },
    # {
    #     "id": 154,
    #     "name": "Alma Mater Studiorum - University of Bologna",
    #     "base_url": "https://www.unibo.it",
    #     "domain": "unibo.it",
    # },
    # {
    #     "id": 155,
    #     "name": "Cardiff University",
    #     "base_url": "https://www.cardiff.ac.uk",
    #     "domain": "cardiff.ac.uk",
    # },
    # {
    #     "id": 156,
    #     "name": "Washington University in St. Louis",
    #     "base_url": "https://www.wustl.edu",
    #     "domain": "wustl.edu",
    # },
    # {
    #     "id": 157,
    #     "name": "Technische Universität Berlin (TU Berlin)",
    #     "base_url": "https://www.tu.berlin",
    #     "domain": "tu-berlin.de",
    # },
    # {
    #     "id": 158,
    #     "name": "Universiti Putra Malaysia (UPM)",
    #     "base_url": "https://www.upm.edu.my",
    #     "domain": "upm.edu.my",
    # },
    # {
    #     "id": 159,
    #     "name": "Ghent University",
    #     "base_url": "https://www.ugent.be",
    #     "domain": "ugent.be",
    # },
    # {
    #     "id": 160,
    #     "name": "Universidad de Chile",
    #     "base_url": "https://www.uchile.cl",
    #     "domain": "uchile.cl",
    # },
    # {
    #     "id": 161,
    #     "name": "University of Wollongong",
    #     "base_url": "https://www.uow.edu.au",
    #     "domain": "uow.edu.au",
    # },
    # {
    #     "id": 162,
    #     "name": "Universiti Kebangsaan Malaysia (UKM)",
    #     "base_url": "https://www.ukm.my",
    #     "domain": "ukm.my",
    # },
    # {
    #     "id": 163,
    #     "name": "University of California, Santa Barbara (UCSB)",
    #     "base_url": "https://www.ucsb.edu",
    #     "domain": "ucsb.edu",
    # },
    # {
    #     "id": 164,
    #     "name": "Hanyang University",
    #     "base_url": "https://www.hanyang.ac.kr",
    #     "domain": "hanyang.ac.kr",
    # },
    # {
    #     "id": 165,
    #     "name": "Kyushu University",
    #     "base_url": "https://www.kyushu-u.ac.jp",
    #     "domain": "kyushu-u.ac.jp",
    # },
    # {
    #     "id": 166,
    #     "name": "Universitat de Barcelona",
    #     "base_url": "https://www.ub.edu",
    #     "domain": "ub.edu",
    # },
    # {
    #     "id": 167,
    #     "name": "Emory University",
    #     "base_url": "https://www.emory.edu",
    #     "domain": "emory.edu",
    # },
    # {
    #     "id": 168,
    #     "name": "University of Florida",
    #     "base_url": "https://www.ufl.edu",
    #     "domain": "ufl.edu",
    # },
    # {
    #     "id": 169,
    #     "name": "University of York",
    #     "base_url": "https://www.york.ac.uk",
    #     "domain": "york.ac.uk",
    # },
    # {
    #     "id": 170,
    #     "name": "Complutense University of Madrid",
    #     "base_url": "https://www.ucm.es",
    #     "domain": "ucm.es",
    # },
    # {
    #     "id": 171,
    #     "name": "University of Reading",
    #     "base_url": "https://www.reading.ac.uk",
    #     "domain": "reading.ac.uk",
    # },
    # {
    #     "id": 172,
    #     "name": "University of Maryland, College Park",
    #     "base_url": "https://www.umd.edu",
    #     "domain": "umd.edu",
    # },
    # {
    #     "id": 173,
    #     "name": "Qatar University",
    #     "base_url": "https://www.qu.edu.qa",
    #     "domain": "qu.edu.qa",
    # },
    # {
    #     "id": 174,
    #     "name": "The University of Newcastle, Australia (UON)",
    #     "base_url": "https://www.newcastle.edu.au",
    #     "domain": "newcastle.edu.au",
    # },
    # {
    #     "id": 175,
    #     "name": "University College Dublin",
    #     "base_url": "https://www.ucd.ie",
    #     "domain": "ucd.ie",
    # },
    # {
    #     "id": 176,
    #     "name": "University of Cape Town",
    #     "base_url": "https://www.uct.ac.za",
    #     "domain": "uct.ac.za",
    # },
    # {
    #     "id": 177,
    #     "name": "Nagoya University",
    #     "base_url": "https://www.nagoya-u.ac.jp",
    #     "domain": "nagoya-u.ac.jp",
    # },
    # {
    #     "id": 178,
    #     "name": "Erasmus University Rotterdam",
    #     "base_url": "https://www.eur.nl",
    #     "domain": "eur.nl",
    # },
    # {
    #     "id": 179,
    #     "name": "University of Liverpool",
    #     "base_url": "https://www.liverpool.ac.uk",
    #     "domain": "liverpool.ac.uk",
    # },
    # {
    #     "id": 180,
    #     "name": "Arizona State University",
    #     "base_url": "https://www.asu.edu",
    #     "domain": "asu.edu",
    # },
    # {
    #     "id": 181,
    #     "name": "University of Calgary",
    #     "base_url": "https://www.ucalgary.ca",
    #     "domain": "ucalgary.ca",
    # },
    # {
    #     "id": 182,
    #     "name": "King Fahd University of Petroleum & Minerals",
    #     "base_url": "https://www.kfupm.edu.sa",
    #     "domain": "kfupm.edu.sa",
    # },
    # {
    #     "id": 183,
    #     "name": "Université catholique de Louvain (UCLouvain)",
    #     "base_url": "https://www.uclouvain.be",
    #     "domain": "uclouvain.be",
    # },
    # {
    #     "id": 184,
    #     "name": "Curtin University",
    #     "base_url": "https://www.curtin.edu.au",
    #     "domain": "curtin.edu.au",
    # },
    # {
    #     "id": 185,
    #     "name": "Technische Universität Wien",
    #     "base_url": "https://www.tuwien.ac.at",
    #     "domain": "tuwien.ac.at",
    # },
    # {
    #     "id": 186,
    #     "name": "Tecnológico de Monterrey",
    #     "base_url": "https://www.tec.mx",
    #     "domain": "tec.mx",
    # },
    # {
    #     "id": 187,
    #     "name": "École Normale Supérieure de Lyon",
    #     "base_url": "https://www.ens-lyon.fr",
    #     "domain": "ens-lyon.fr",
    # },
    # {
    #     "id": 188,
    #     "name": "University of Gothenburg",
    #     "base_url": "https://www.gu.se",
    #     "domain": "gu.se",
    # },
    # {
    #     "id": 189,
    #     "name": "Universiti Teknologi Malaysia",
    #     "base_url": "https://www.utm.my",
    #     "domain": "utm.my",
    # },
    # {
    #     "id": 190,
    #     "name": "McMaster University",
    #     "base_url": "https://www.mcmaster.ca",
    #     "domain": "mcmaster.ca",
    # },
    # {
    #     "id": 191,
    #     "name": "Queensland University of Technology (QUT)",
    #     "base_url": "https://www.qut.edu.au",
    #     "domain": "qut.edu.au",
    # },
    # {
    #     "id": 192,
    #     "name": "Universite libre de Bruxelles",
    #     "base_url": "https://www.ulb.ac.be",
    #     "domain": "ulb.ac.be",
    # },
    # {
    #     "id": 193,
    #     "name": "Albert-Ludwigs-Universitaet Freiburg",
    #     "base_url": "https://www.uni-freiburg.de",
    #     "domain": "uni-freiburg.de",
    # },
    # {
    #     "id": 194,
    #     "name": "Ecole des Ponts ParisTech",
    #     "base_url": "https://www.enpc.fr",
    #     "domain": "enpc.fr",
    # },
    # {
    #     "id": 195,
    #     "name": "Wuhan University",
    #     "base_url": "https://www.whu.edu.cn",
    #     "domain": "whu.edu.cn",
    # },
    # {
    #     "id": 196,
    #     "name": "Hokkaido University",
    #     "base_url": "https://www.hokudai.ac.jp",
    #     "domain": "hokudai.ac.jp",
    # },
    # {
    #     "id": 197,
    #     "name": "Universidad de los Andes",
    #     "base_url": "https://uniandes.edu.co",
    #     "domain": "uniandes.edu.co",
    # },
    # {
    #     "id": 198,
    #     "name": "University of Minnesota Twin Cities",
    #     "base_url": "https://twin-cities.umn.edu",
    #     "domain": "umn.edu",
    # },
    # {
    #     "id": 199,
    #     "name": "Universidad Autónoma de Madrid",
    #     "base_url": "https://www.uam.es",
    #     "domain": "uam.es",
    # },
    # {
    #     "id": 200,
    #     "name": "Indian Institute of Technology Delhi (IITD)",
    #     "base_url": "https://www.iitd.ac.in",
    #     "domain": "iitd.ac.in",
    # },
]
